chore: workspace path debug

diff --git a/.github/actions/check-version/action.yml b/.github/actions/check-version/action.yml
--- a/.github/actions/check-version/action.yml
+++ b/.github/actions/check-version/action.yml
@@ -8,6 +8,9 @@ inputs:
   python-version:
     description: Python version
     required: false
+  repository:
+    description: GitHub repository in the format owner/repo
+    required: true
   package-manager:
     description: Package manager to use (e.g. npm, poetry)
     required: true
@@ -63,17 +66,13 @@ runs:
 
     - name: Run version check script
       id: app_version_step
-      env:
-        REPOSITORY: ${{ github.repository }}
       shell: sh
       run: |
-        echo "GITHUB_REPOSITORY: ${{ env.REPOSITORY }}"
-        
-        latest_release_version=$(curl -s https://api.github.com/repos/${{ env.REPOSITORY }}/releases/latest | jq -r '.tag_name // empty')
+        latest_release_version=$(curl -s https://api.github.com/repos/${{ inputs.repository }}/releases/latest | jq -r '.tag_name // empty')
         echo "Latest release: $latest_release_version"
 
         if [ -z "$latest_release_version" ]; then
-          echo "Error: No releases found for repository '${{ env.REPOSITORY }}' or 'tag_name' is missing in the latest release." >&2
+          echo "Error: No releases found for repository '${{ inputs.repository }}' or 'tag_name' is missing in the latest release." >&2
           exit 1
         fi
 
